/**
 * Act two, flat-playful edition: the real captured answer, shown as the
 * product's own ivory paper inside a flat white card. The question sits in a
 * cobalt-bordered bubble above it, and the copy tells the draft-then-swap
 * truth. Nothing staged: Markdown + NotebookViewer are the product's own
 * renderers on the product's own output.
 */
import { motion } from "motion/react";
import { Sparkles, BookMarked, CheckCircle2, Volume2 } from "lucide-react";
import { parseTeachingSections } from "../utils";
import { Markdown } from "../Markdown";
import { NotebookViewer } from "../NotebookViewer";
import { REAL_QUESTION, REAL_ANSWER } from "./realAnswer";
import { useCalm, fadeUp, sheetRise } from "./reveals";

const parsed = parseTeachingSections(REAL_ANSWER);

const CHIPS = [
  { icon: Sparkles, label: "Still fuzzy?" },
  { icon: CheckCircle2, label: "Deep-check" },
  { icon: BookMarked, label: "Save lines" },
  { icon: Volume2, label: "Listen" },
];

export default function AnswerAct() {
  const calm = useCalm();

  return (
    <section id="watch" className="bg-page px-5 py-16 text-ink md:px-8 md:py-24" aria-label="A real answer from Clarify.AI">
      <div className="mx-auto max-w-6xl">
        <div className="max-w-3xl">
          <motion.p {...fadeUp(calm)} className="kod-pill inline-block bg-lime text-pill-ink">
            generated live &middot; unedited
          </motion.p>
          <motion.h2
            {...fadeUp(calm, calm ? 0 : 0.08)}
            className="kod-display landing-balance mt-4 text-[clamp(1.9rem,5vw,3rem)] leading-[1.08] text-ink"
          >
            This is the product, not a picture of it.
          </motion.h2>
          <motion.p {...fadeUp(calm, calm ? 0 : 0.16)} className="landing-pretty mt-5 max-w-2xl text-[15px] leading-relaxed text-ink-dim md:text-base">
            You type the sentence exactly as you heard it. You do not have to
            phrase it well. Then you watch the teacher work: a draft writes
            itself out in front of you, the way rough work fills the side of a
            page. That draft is not the answer you keep. When it is complete,
            an examiner pass reads the whole thing, checks the facts and the
            calculations, and the corrected, verified answer quietly takes its
            place. What stays on your screen, and what goes into your notebook,
            is the checked final, never the first attempt.
          </motion.p>
        </div>

        {/* The question, asked the way a student actually asks */}
        <motion.div {...sheetRise(calm)} className="mt-10 flex flex-col items-end">
          <p className="kod-display mb-1.5 text-xs text-ink-dim">You, at 11:04 pm</p>
          <div className="max-w-xl rounded-[2px] border-2 border-cobalt-bright bg-page p-4 text-sm leading-relaxed text-ink md:text-base">
            {REAL_QUESTION}
          </div>
        </motion.div>

        {/* The answer: the product's own paper inside the flat card */}
        <motion.div {...sheetRise(calm)} className="mt-6 rounded-[2px] border-2 border-ink-line bg-page p-2 sm:p-3">
          <div className="flex flex-wrap items-center gap-2 px-2 py-2">
            <span className="kod-pill bg-cobalt text-white">Clarify.AI</span>
            <span className="kod-pill bg-chip text-ink">CBSE profile</span>
            <span className="kod-pill bg-chip text-ink">Hinglish</span>
            <span className="kod-pill bg-chip text-ink">2 July 2026</span>
            <span className="kod-pill ml-auto hidden bg-lime-pale text-pill-ink sm:inline-block">open the tabs, they work</span>
          </div>
          <div className="lit-sheet rounded-[2px] bg-editorial-ivory p-4 text-editorial-charcoal sm:p-6 md:p-8">
            <div className="text-sm leading-relaxed md:text-base">
              {parsed.preamble && (
                <div className="mb-3">
                  <Markdown>{parsed.preamble}</Markdown>
                </div>
              )}
              <NotebookViewer sections={parsed.sections} />
              {/* The real action row under every answer, kept in step with App.tsx. */}
              <div aria-hidden="true" className="pointer-events-none mt-3 flex flex-wrap items-center gap-1.5 border-t border-editorial-line-light pt-2.5 select-none">
                {CHIPS.map((c) => (
                  <span key={c.label} className={`flex items-center gap-1.5 whitespace-nowrap rounded-full border border-editorial-line-light bg-editorial-stone px-3 py-1 text-xs text-editorial-sage ${c.label === "Listen" ? "sm:ml-auto" : ""}`}>
                    <c.icon size={12} /> {c.label}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </motion.div>

        <p className="landing-pretty mt-4 max-w-3xl text-[13px] leading-relaxed text-ink-dim">
          Generated by Clarify.AI on 2 July 2026 for a CBSE profile in Hinglish.
          Nothing above was staged or edited: the flowchart, the cricket question,
          the shopping&#8209;cart analogy, all of it came from the teacher.
        </p>
      </div>
    </section>
  );
}
